sudo: required
language: ruby
services:
- docker
install:
- bundle install
script:
- kitchen test
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: RkJU6eZPcX6xRNpMK52hUrCONdmTvruLnTnETXsEQ1/w4nAa7Xw14UDpo2ApTjyGbbjDDKzHCOCqe2dT24G1RktkLz1vkvZrCrr80lmAvsvFoj0Sou9Ec9OoPwJ6Ny+W3EKolLHdIOv0KCC2CjWE2CVjYOgZQXnO7b16XTJdd8f2Vz2oGrAuDxh6kOcCE4q/avgxkLiNFXWK3nxIq3nEFgSOV57Wvg8IAq7g4wW/hIZ1T0fTN0iuA4ujEZSnA4UMngc1fNrV/ItsnHMXG1R03U1TSTBSXot2U9qdeTbyoZvZFD2fzM1zt9wqdHzjWvK5zU7PaOOjvjNmN8BVlCf+6QkCBAvIOf6gGgel3DEHquqbT1jfGeYaameH7dqjO0Djvyrenxzx4aYGUHYtPr9zAjFcJvBJ4PMKgKsGEXf17kJRZAc2A/VPFJb4pALfcuMeRlhNnbUa20MXxg+jMdPeioc6ytq4zNiePKkNWXGnxN5bd+U7TnUOos0bFnfJ1q2qzyaATtDA2i6dyFYaacju+fNuh9iWiAlNeft56wP11spIpeu0AUedbTxNiNaSJkv4EGmAm1gysUX6r2+lsx04F9G5BmitTnxbZAyKweMhPJYq96Cb9NB/RNiHCTnzMKxW4s5gB3SVuvaE0acZXEp8KCUujYWWmQU+SjJFffzclcQ=
